### ISSUE TITLE
SQL/Doctrine exception initializing permissions

### ISSUE THREAD

**Issue by danielrestrepo** [Fahrenheit451Tecnologia/tm-rbac-bundle#2]
Given the following simple permissions configuration:
```yaml
tm_rbac:
    models:
        permission: AppBundle\Entity\Permission
        role: AppBundle\Entity\Role
        user: AppBundle\Entity\User
    listeners:
        permission: true
    permissions:
        get_models: Get list of models
        get_tags: Get list of tags
```
And the permission mapping:
```php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use TM\RbacBundle\Model\Permission as BasePermission;

/**
 * Class Permission
 * @package AppBundle\Entity
 *
 * @ORM\Entity(repositoryClass="TM\RbacBundle\Repository\PermissionRepository")
 * @ORM\Table(name="permissions", schema="gallery")
 */
class Permission extends BasePermission
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="guid")
     * @ORM\GeneratedValue(strategy="UUID")
     *
     * @var string
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
    }
}
```
When execute the command `tm:rbac:initialize-permissions` I am getting the following errors:
```bash
[Doctrine\DBAL\Exception\DriverException]                                    
  An exception occurred while executing 'SELECT t0.permission_name AS permission_name_1, t0.id AS id_2 FROM gallery.permissions t0 WHERE t0.id = ?' with params ["get_models"]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for uuid: "get_models"

[Doctrine\DBAL\Driver\PDOException]                                          
  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for uuid: "get_models"
```
Not sure where to start debugging it. Please help.
