### ISSUE TITLE
You do not have the "get_models" permission

### ISSUE THREAD

**Issue by danielrestrepo** [Fahrenheit451Tecnologia/tm-rbac-bundle#3]
Rbac configuration:
```yaml
tm_rbac:
    models:
        permission: AppBundle\Entity\Permission
        role: AppBundle\Entity\Role
        user: AppBundle\Entity\User
    listeners:
        permission: true
    permissions:
        get_models: Get list of models
        get_tags: Get list of tags
```
Controller method:
```php
/**
     * @Permission("get_models")
     * @Route("/models/", name="get_models")
     * @Method({"GET"})
     *
     * @param Request $request
     * @return Model[]|array
     */
    public function indexAction(Request $request)
    {
        $page = $request->query->get('page', 1);

        $queryBuilder = $this->em
            ->getRepository(Model::class)
            ->findAllQueryBuilder('model');

        $adapter = new DoctrineORMAdapter($queryBuilder);
        $pagerFanta = new Pagerfanta($adapter);
        $pagerFanta->setMaxPerPage(10);
        $pagerFanta->setCurrentPage($page);

        return $pagerFanta;
    }
```
Authentication is handled by `lexik/jwt-authentication-bundle` and it works normally, although I am not sure if it has anything to do with permissions verification.

Roles table:   
![selection_008](https://user-images.githubusercontent.com/8768725/29575761-1da48356-872b-11e7-8453-ee98a6c8d6e8.png)
Users table:
![selection_009](https://user-images.githubusercontent.com/8768725/29575817-4482ade0-872b-11e7-842c-c3228b1756d9.png)
Permissions table:
![selection_010](https://user-images.githubusercontent.com/8768725/29575854-67b5c02c-872b-11e7-833d-c35ecbb6794b.png)
Roles and permissions table:
![selection_011](https://user-images.githubusercontent.com/8768725/29575900-8c413c1e-872b-11e7-8b14-327c180d7023.png)
Users, roles table:
![selection_012](https://user-images.githubusercontent.com/8768725/29575929-ac595f5e-872b-11e7-839b-0aa317011790.png)

You can see that data wise everything seems to be correct. What else would you need to sort this out?
